### ISSUE TITLE
issue while adding custom model

### ISSUE THREAD

**Issue by souvikm99** [spring98/flutter-yolo-realtime-plugin#6]
Running Gradle task 'assembleDebug'...                              6.1s
✓  Built build/app/outputs/flutter-apk/app-debug.apk.
I/flutter (18519): The Dart VM service is listening on ************************************
E/AndroidRuntime(18519): FATAL EXCEPTION: pool-3-thread-1
E/AndroidRuntime(18519): Process: com.spring98.yolo_realtime_plugin_example, PID: 18519
E/AndroidRuntime(18519): com.facebook.jni.CppException: isTuple() INTERNAL ASSERT FAILED at "../../../../src/main/cpp/libtorch_include/arm64-v8a/ATen/core/ivalue_inl.h":1101, please report a bug to PyTorch. Expected Tuple but got String
E/AndroidRuntime(18519): Exception raised from toTuple at ../../../../src/main/cpp/libtorch_include/arm64-v8a/ATen/core/ivalue_inl.h:1101 (most recent call first):
E/AndroidRuntime(18519): (no backtrace available)
E/AndroidRuntime(18519):        at org.pytorch.NativePeer.forward(Native Method)
E/AndroidRuntime(18519):        at org.pytorch.Module.forward(Module.java:49)
E/AndroidRuntime(18519):        at com.spring98.yolo_realtime_plugin.CameraView$YoloImageAnalyzer.analyze(YoloRealtimePlugin.kt:255)
E/AndroidRuntime(18519):        at androidx.camera.core.ImageAnalysis.lambda$setAnalyzer$2(ImageAnalysis.java:528)
E/AndroidRuntime(18519):        at androidx.camera.core.ImageAnalysis$$ExternalSyntheticLambda2.analyze(Unknown Source:2)
E/AndroidRuntime(18519):        at androidx.camera.core.ImageAnalysisAbstractAnalyzer.lambda$analyzeImage$0$androidx-camera-core-ImageAnalysisAbstractAnalyzer(ImageAnalysisAbstractAnalyzer.java:286)
E/AndroidRuntime(18519):        at androidx.camera.core.ImageAnalysisAbstractAnalyzer$$ExternalSyntheticLambda1.run(Unknown Source:14)
E/AndroidRuntime(18519):        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
E/AndroidRuntime(18519):        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
E/AndroidRuntime(18519):        at java.lang.Thread.run(Thread.java:1012)

**Comment by spring98** [comment]
sorry for late reply!

I think it would be helpful if you could answer a few questions.

1. Which version of yolo did you use?

2. How many GPUs were connected and used during training?

thank you

**Comment by Dough-su** [comment]
You can check if you forgot to change androidModelWidth and androidModelHeight. I spent nearly 4 hours debugging the kotlin part of the code and finally found that The size of tensor a (40) must match the size of tensor b (80) at non -singleton dimension 3

**Comment by souvikm99** [comment]
i am using yolov5 and i trained it using colab A100 GPU and T4 in some versions.
